### ISSUE TITLE
spec-komp.ru

### ISSUE THREAD

**Issue by spiri-leo** [MonyaTechnik/themtfilters#3]
This is Ucoz registered domain, with counters on a this website. Some registered Ucoz websites, with statistics.

![alt text](https://i.ibb.co/7JC2H6F/57.png)

This link is metrics:
<pre>
spec-komp.com/stat/
</pre>

This is impossible block. How to block on some all Ucoz registered domains?

Operating system: Windows 21H1 19043.1165
Browser: Google Chrome 92.0.4515.131
Adblocker: uBlock Origin 1.37.2

**Comment by MonyaTechnik** [comment]
Ok, i testing my filter. Got errors, delete that.

**Comment by spiri-leo** [comment]
It blocked! Not errors!
