### ISSUE TITLE
I found open website analytics is Aurora

### ISSUE THREAD

**Issue by spiri-leo** [MonyaTechnik/themtfilters#4]
I found this analytics on d3ward's GitHub website. Here's blocking links:
```
||aurora-d3.herokuapp.com^
||aurora-analytics.herokuapp.com/v2/collect
```
This official website: https://useaurora.app

Here's screenshots:
![1](https://i.ibb.co/dPxBSrn/78.png)
![2](https://i.ibb.co/jM9J99D/79.png)

This blocking links added on not-completed filter for copying.

**Comment by MonyaTechnik** [comment]
I added on my adblocker, got errors, delete that. Today not adding this links now, creating not-completed filter for copying, and copying completed filter for this filters.

**Comment by d3ward** [comment]
Hello ,  Why blocking Aurora ? This it's a self-hosting analytics tool that is privacy friendly with no cookie , which it's included in all my websites/projects only . 
If anyone that is using my projects blocks the domain , i will not be able to have an updated count of visitors with some minimal infos about users ( country ,platform , browser and referrer ) there is no user profiling , so it's very privacy friendly and not intended as a classic analytics service .
I am available to answer any questions regarding the privacy policy of the analytic tool, my websites/projects or anything else

**Comment by spiri-leo** [comment]
> Hello ,  
> Why blocking Aurora ? This it's a self-hosting analytics tool that is privacy friendly with no cookie , which it's included in all my websites/projects only . 
> If anyone that is using my projects blocks the domain , i will not be able to have an updated count of visitors with some minimal infos about users ( country ,platform , browser and referrer ) there is no user profiling , so it's very privacy friendly and not intended as a classic analytics service .
> I am available to answer any questions regarding the privacy policy of the analytic tool, my websites/projects or anything else

Already fixed.
