### ISSUE TITLE
ozon.ru

### ISSUE THREAD

**Issue by spiri-leo** [MonyaTechnik/themtfilters#5]
[//]: # (Description enter this:)

The product viewer is nothing.

[//]: # (Copy screenshot url)

<details><summary>Screenshot:</summary>

![image](https://i.ibb.co/v4Wq4B4/85.png)
</details><br/>

[//]: # (If image is NSFW, create the link button to open image)

[//]: # (Please enter your information)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 21H1 19043.1202
Operating system version (Android/iOS) | Android 11 (MIUI)
Browser:                               | Google Chrome 93.0.4577.63
Adblock version:                       | uBlock Origin 1.37.2

**Comment by MonyaTechnik** [comment]
Remove Ozon's annoyances on BlkFckAds please.

**Comment by spiri-leo** [comment]
> Remove Ozon's annoyances on BlkFckAds please.

Ok

**Comment by spiri-leo** [comment]
I fixed, here's commit on GitHub:
https://github.com/MonyaTechnik/themtfilters/commit/c9483f03f08f66b23bf75bc71627d3c0d2c7801f

**Comment by MonyaTechnik** [comment]
Thanks!
