### ISSUE TITLE
adguard.com

### ISSUE THREAD

**Issue by spiri-leo** [MonyaTechnik/themtfilters#6]
[//]: # (Description enter this:)
Not header on AdGuard official website

[//]: # (Copy screenshot url)

<details><summary>Screenshot:</summary>

![image](https://i.ibb.co/rwRRWss/87.png)
</details><br/>

[//]: # (If image is NSFW, create the link button to open image)

[//]: # (Please enter your information)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 19043.1202
Operating system version (Android/iOS) | Android 11
Browser:                               | Google Chrome 93.0.4577.63
Adblock version:                       | uBlock Origin 1.37.2

**Comment by MonyaTechnik** [comment]
Ok, i fix it.

**Comment by MonyaTechnik** [comment]
Fixed successful.
Here commit: https://github.com/MonyaTechnik/themtfilters/commit/1fcac83374512184be73bb5299fc24fb688dfbb8#diff-8c083646952ba9581185a15feadf300e5c607ca98e47a501ddf8680c0998975a
